[TI-2583] Support both lz4 library for Ubuntu 20.04 and Ubuntu 18.04 for squashmerge
mgorny/squashmerge pull request #3
Opened 2023-07-20 01:06 UTC by xihongzhuang-bc

Also, in the liblz4-1 package 1.9.2-2ubuntu0.20.04.1, we need to allocated enough buffer to be used inside the API call of lz4 library to avoid potential data overflow.

2023-07-20 06:34 UTC, mgorny requested changes
Please put at least the minimal effort to follow the original coding style, and make commit messages clear in themselves, without referring to opaque identifiers and things requiring third-party sites to figure out what they mean.

2023-07-20 19:44 UTC, xihongzhuang-bc commented
> Please put at least the minimal effort to follow the original coding style, and make commit messages clear in themselves, without referring to opaque identifiers and things requiring third-party sites to figure out what they mean.

I don't quite follow what you mean here? Can you spot the places or identifiers that are not following the original coding style? Thanks a lot for your review.

2023-07-20 23:12 UTC, closed without merging

2023-07-21 06:01 UTC, mgorny commented on src/compressor.c
> +			//now we are calling the new lz4 library in Ubuntu 20.04, which is liblz4-1:amd64, 1.9.2-2ubuntu0.20.04.1
The code doesn't use C++ comments, it's C89. Also, use upstream lz4 release versions, not Ubuntu.

2023-07-21 06:01 UTC, mgorny commented on src/compressor.c
> +			max_dest_size = LZ4_compressBound( length );
Extraneous space.

2023-07-21 06:01 UTC, mgorny commented on src/compressor.c
> +			void *dest_new = calloc(max_dest_size, 1);
`*` before space, not after.

2023-07-21 06:01 UTC, mgorny commented on src/compressor.c
> +				*/
Don't copy the whole header file here.

2023-07-21 06:01 UTC, mgorny commented on src/compressor.c
> +				fprintf(stderr, "20.04 LZ4_compress_HC: source size: %lu, max_dest_size: %lu, out_bytes:%lu, expected size: %lu\n", length, max_dest_size, out_bytes, out_size);
I can't say the original file is 100% consistent but keep below 80 cols. Also you use spaces inconsistently. Also `20.04` is entirely meaningless to the end user, and this whole thing looks like debug, not error output.